### ISSUE TITLE
Show shortlink on Non-orphan visits list.

### ISSUE THREAD

**Issue by gcarrarom** [shlinkio/shlink-web-component#244]
#### Summary

When visiting the Non-orphan visits view, I can't find which shortlink was the one visited. I would like to have an entry at the table showing which shortlink was visited. Here's a suggestion of what this could look like:
![CleanShot 2023-05-08 at 16 24 07](https://user-images.githubusercontent.com/10549675/236926657-5a4d74f7-7be7-4849-bb2a-ecb7f2c1a77b.png)

This could potentially be showing the labels or even just a link to the shortlink page.

**Comment by ejohb** [comment]
Thanks for your work on this!

I've updated, but still can't see the shortlink in `non-orphan-visits/list`. Do I need to do anything to enable it?

> Server: [v4.1.0](https://github.com/shlinkio/shlink/releases/v4.1.0) - Client: [v4.1.1](https://github.com/shlinkio/shlink-web-client/releases/v4.1.1)

**Comment by acelaya** [comment]
> I've updated, but still can't see the shortlink in non-orphan-visits/list

This issue is still not implemented 😅

It's just unblocked now, because the backend now returns all required info.

**Comment by ejohb** [comment]
Oh, I'd misunderstood. Thanks for explaining!

**Comment by acelaya** [comment]
I'm going to treat this as a bug, as in "the server is returning the information, but the client is using the wrong logic to determine when to show it, resulting in the info not being displayed"

**Comment by acelaya** [comment]
This is now implemented. I just need to fix one last bug, and then I'll release the fixes with shlink-web-client 4.1.2

**Comment by acelaya** [comment]
I have just released shlink-web-client 4.1.2, which includes this.

As long as the server is Shlink >=4.1, all kinds of visits will now show the visited URL column in the visits table.

**Comment by ejohb** [comment]
Works great. Thanks so much for your efforts!
