### ISSUE TITLE
QR code modal ignores default errorCorrection value

### ISSUE THREAD

**Issue by inukiwi** [shlinkio/shlink-web-component#382]
### shlink-web-client version

4.1.2

### How do you use shlink-web-client

https://app.shlink.io

### Current behavior

When opening the QR code modal it prepopulates the parameters in the URL, therefore ignoring the default values set on the Shlink server. This causes issues for us because we need a higher default errorCorrection value to still work with the custom logo feature.

### Expected behavior

Ideally the modal settings would be populated from the default settings configured on the Shlink server, but I'm not sure if that is possible.
Another option would be to leave the settings empty when opening the modal, so it would just use the basic url without parameters.

### Minimum steps to reproduce

- Set custom QR code environment variables
- Open the QR code modal on the web client

**Comment by inukiwi** [comment]
Thanks for looking into it!

Defining the config in the web client would all be clientside right? It's a definitely nice option, but it would also require all users to be made aware of the proper settings, having them enter those on every client and it would be hard to provision new settings. 

I've made a small pull request that takes the approach of not appending any params initially.

**Comment by acelaya** [comment]
I'm experimenting with something on these lines, which does not set an initial value for any of the params, hence falling back to the server defaults, and evolves the UI so that all params have an option which represents "use the default value":

https://github.com/user-attachments/assets/fe68e7b0-2a57-451f-a9b8-c0b7fd83b2e2
