### ISSUE TITLE
Show the location on a map

### ISSUE THREAD

**Issue by PinguDEV-original** [shlinkio/shlink-web-component#386]
### Summary

Right now you can see from which country and then from which city requests came from. It would be really cool to have this on a map (like Dub.co has it for example).

### Use case

Would just look better and would be easier to understand.

**Comment by acelaya** [comment]
This is already supported. 

https://github.com/shlinkio/shlink-web-component/assets/2719332/e9bc830e-bbf2-4328-8b83-525ca4f6ce5e
