### ISSUE TITLE
Add custom user agent column to list view

### ISSUE THREAD

**Issue by theofficialgman** [shlinkio/shlink-web-component#435]
See https://github.com/shlinkio/shlink-web-component/issues/434

The previous issue got too off topic (apparently) and was locked.
The previous issue's feature request was clear and concise in the first post https://github.com/shlinkio/shlink-web-component/issues/434#issue-2528931651

The feature can be best described in the sentence from that post:

> In usecases where the user agent is customized by the sender (or simply not in the hardcoded list) it would be nice to view this information within the web interface.

Where the only option that would be required would be to show the whole user agent instead of the arbitrary browser/OS parsing.

The parsing as describe here https://github.com/shlinkio/shlink-web-component/issues/434#issuecomment-2358761799 is beyond the scope of this feature request and would be an additional feature (only after this one was implemented). Such a feature would best be summed up as "custom regex sort/parsing operations on user agents" and could allow for much more complex (and useful) parsing of the user agents.

**Comment by theofficialgman** [comment]
A toggle basically would be added to switch "modes"

Current:
![image](https://github.com/user-attachments/assets/2b92c426-fe4f-420c-8f31-a3673bb400d2)

A (very quick) mockup:
<img width="731" alt="Screenshot 2024-09-18 160447" src="https://github.com/user-attachments/assets/b336d4d4-136b-487a-9947-eeca53daf552">

**Comment by acelaya** [comment]
> The previous issue got too off topic (apparently) and was locked.
> The previous issue's feature request was clear and concise in the first post #434 (comment)

This is your last warning. If you don't stop with the passive-aggressive tone, you'll get a permanent ban from this project. 

As per the feature request, it is now well described and makes sense.
