### ISSUE TITLE
Filtered CSV export broken

### ISSUE THREAD

**Issue by svenger87** [shlinkio/shlink-web-component#58]
### Shlink version

v3.6.3

### PHP version

8.2.8

### How do you serve Shlink

Self-hosted nginx

### Database engine

MariaDB

### Database version

10.11.3

### Current behavior

If i filter the short URL list the CSV Export button shows the correct number of filtered URLs.
But if i export the CSV file all known short URLs are exported to the csv file.

### Expected behavior

Export only the filtered results.

### How to reproduce

Filter short URL list by any name. Export filtered list as CSV. CSV will contain all URLs known on the server. Not only the filtered results.

**Comment by acelaya** [comment]
This is reproducible in shlink-web-client's `main` branch, but it is no longer reproducible in `shlink-web-component`, which is the new component containing the main logic and UI to interact with Shlink.

I'm going to close this as completed.
